version: 2

defaults: &defaults
  working_directory: ~/project/vue
  docker:
    # change to some generic circleci images
    - image: myorg/ci

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-vue-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-vue-{{ .Branch }}-
            - v1-vue-
      - run: echo "install dependencies"
      - save_cache:
          key: v1-vue-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - persist_to_workspace:
          root: ~/project
          paths:
            - vue

  lint-flow-types:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: echo "run linting tests"

  test-cover:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: echo "run coverage tests"
      - run:
        # let's leave this but simplify
         name: report coverage stats for non-PRs
         command: |
           if [[ -z $CI_PULL_REQUEST ]]; then
             ./node_modules/.bin/codecov
           fi

  test-e2e:
    <<: *defaults
    docker:
      - image: myorg/ci
      - image: myorg/postgres:9.4.1
        environment:
          POSTGRES_USER: root
    steps:
      - attach_workspace:
          at: ~/project
      - run: echo "run end to end tests"

  trigger-regression-test:
    <<: *defaults
    steps:
      - run:
          name: regression testing
          command: |
            echo "cool done"

  deploy:
    <<: *defaults
    steps:
      - run: echo "ship it!"

workflows:
  version: 2
  install-and-parallel-test:
    jobs:
      - install
      - test-cover:
          requires:
            - install
      - lint-flow-types:
          requires:
            - install
      - test-e2e:
          requires:
            - install
      - trigger-regression-test:
          filters:
            branches:
              only:
                - "2.6"
                - regression-test
          requires:
            - test-cover
            - lint-flow-types
            - test-e2e
      - deploy:
          filters:
            branches:
              only:
                - master